### ISSUE TITLE
To-Do List relacionada com o iReports/JasperReports

### ISSUE THREAD

**Issue by iuryamicussi** [iuryamicussi/TrabalhoCrisParte2#6]
- [x] Verificar os arquivos necessários para funcionar

- [x] Baixar e instalar no notebook do Iury

- [x] Criar os relatórios do Clientes, Fornecedores e Produtos
